#!/usr/bin/env python3

import os
import sys
import jump

if len(sys.argv) > 1 and sys.argv[1] == '--complete':
    jump.complete(len(sys.argv) > 2 and sys.argv[2] or '')
    exit(0)
elif len(sys.argv) > 1 and sys.argv[1] == '--dump':
    jump.dump()
    exit(0)
elif len(sys.argv) > 2 and sys.argv[1] == '--delete':
    jump.delete_entry(sys.argv[2])
    exit(0)
try:
    dir = jump.find_best_dir(
        len(sys.argv) > 1 and sys.argv[1] or os.getenv("HOME"))
    print(dir)
except:
    jump.log(sys.exc_info()[0])
